"""empty message

Revision ID: 96364e131d3f
Revises: c3cde425087d
Create Date: 2019-03-03 19:39:32.190913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96364e131d3f'
down_revision = 'c3cde425087d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
